name: Barcode CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build BarcodeStandard/BarcodeStandard.csproj --configuration Release --no-restore
